.TH "JAVA-CONFIG" "1" "September 2011" "java-config 2.2.0" "User Commands"
.SH "NAME"
java-config - The Java configuration tool for Gentoo
.SH "SYNOPSIS"
.B java-config
\fI[options]\fB
.SH "DESCRIPTION"
.PP 
.I java-config
Is used to query/set properties of your system's Java environment. It can be
used to list available VMs and java packages.
.PP 
In addition, it is used by Portage as a common interface to querying 
properties about the various JVMs.
.SH "OPTIONS "
.TP
\fB--select-vm=VM\fI
Use this vm instead of the active vm when returning information.
.TP 
\fB-c, --javac\fI
Show full path to currently selected Java compiler.
.TP 
\fB-j, --jar\fI
Show full path to currently selected
.I jar 
command.
.TP 
\fB-o, -O, --java-home, --jdk-home, --jre-home\fI
Print JAVA_HOME of currently selected JVM.
.TP 
\fB-t, --tools\fI
Print path to tools.jar
.TP 
\fB-v, --java-version\fI
Query current JVM for version.
.TP 
\fB-p [pkg1[-SLOT],pkg2[-SLOT],...] --classpath[=package1,package2,...]\fI
Calculate classpath for a package. If a package is installed in different 
slots you can also specify the slot to get the specific classpath informations.
.TP
\fB-g VAR, --get-env=VAR\fI
Print an environment variable from the active VM.
.TP 
\fB\-e command, --exec=command\fI
Run the specified JDK/JRE utility of the active vm, such as 
.I keytool 
,
.I rmic
and others.
.
.TP 
\fB-i PACKAGE(S), --library=PACKAGE(S)\fI
Print java library paths for these packages. Used for example in wrapper
scripts like this: -Djava.library.path=$(java-config -i swt-3). Follows the same
pkg[-SLOT] convention as for example --classpath.
.
.TP 
\fB-l, --list-available-packages\fI
List available Java packages. Used for selection by
.I --classpath
.TP 
\fB-L, --list-available-vms\fI
Lists available JVMs.
.TP 
\fB-f, --show-active-vm\fI
Show the JVM that's currently active, as set by eselect java-vm.
.TP 
\fB-n, --nocolor\fI
Turn off all colors.
.TP 
\fB-P <vm-id>, --print=<vm-id>\fI
Print the environment information for the specified virtual machine. 
.TP 
\fB-d, --with-dependencies\fI
Include package dependencies in --classpath and --library calls.
.TP 
\fB-r, --runtime\fI
Print the runtime classpath.
.TP 
\fB--package=PACKAGE(S)\fI
Retrieve a value from a packages package.env file, value is specified by --query.
.TP
\fB-q QUERY, --query=QUERY\fI
Value to retieve from packages package.env file, specified by --package.
.TP
\fB--get-virtual-providers=PACKAGE(S)\fI
Return a list of packages that provide a virtual.

.SH "MAINTAINER"
java@gentoo.org
.SH "AUTHORS"
Karl Trygve Kalleberg <karltk@gentoo.org>
.br 
Adrian Almenar <strider@gentoo.org>
.br 
Jason Mobarak <aether@gentoo.org>

.SH "BUGS"
Report any bugs you find to https://bugs.gentoo.org/.

.SH "SEE ALSO"
env-update(5)
.TP 
The \fI/usr/bin/java-config\fR script. 
