#!/usr/bin/env bash
version=${1}
if [[ -z ${version} ]]; then
	echo "I want a version"
	exit 1
fi
svn up
svn2cl --authors=AUTHORS
sed -i "s/package_version =.*/package_version = \'${version}\',/" setup.py
python setup.py sdist --force-manifest --formats=bztar

cp -v dist/java-config-${version}.tar.bz2 $(portageq envvar DISTDIR)
