#!/bin/bash

if [[ -n ${GENTOO_VM} ]]; then
	vmpath=/etc/java-config/vms/${GENTOO_VM}/
elif [[ -h ${HOME}/.gentoo/user-vm ]]; then
	vmpath=${HOME}/.gentoo/user-vm/
else
	vmpath=/etc/java-config/vms/system-vm/
fi
tool=$(basename $0)
bin=${vmpath}/bin/${tool}
args=""
[[ "${tool}" == "javac" ]] && args="${GENTOO_JAVACFLAGS}"
[[ "${tool}" =  "java" ]] && args="${GENTOO_JAVAFLAGS}"

if [[ -x ${bin} ]]; then
	exec ${bin} ${args} "${@}"
else
	echo "Want too run ${bin} but it does not exist or is not executable" >&2
	exit 1
fi
